# Generated by Django 5.2.8 on 2025-11-28 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemdeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_conclusao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('prioridade', models.CharField(max_length=50, verbose_name='prioridade')),
                ('observacao', models.CharField(max_length=100, verbose_name='observacao')),
                ('diagnostico', models.CharField(max_length=100, verbose_name='diagnostico')),
                ('categoria', models.CharField(max_length=50, verbose_name='categoria')),
                ('problema_relatado', models.CharField(max_length=100, verbose_name='problema_relatado')),
                ('valor_servico', models.CharField(max_length=50, verbose_name='valor_servico')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.cliente')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamento.equipamento')),
            ],
        ),
    ]
