# Generated by Django 5.2.8 on 2025-11-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_marca', models.CharField(max_length=50, verbose_name='Modelo e Marca')),
                ('patrimonio', models.CharField(max_length=50, verbose_name='Patrimonio')),
                ('num_serie', models.CharField(max_length=50, verbose_name='Número de Série')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
