# Generated by Django 5.2.8 on 2025-11-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor')),
            ],
        ),
    ]
